# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.0

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.2.4
      # Runs a set of commands using the runners shell
      - name: Install Haxelib
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp > nul
          haxelib install lime --quiet
          haxelib install openfl --quiet
          haxelib --never install flixel 4.0.9
          haxelib run lime setup flixel --quiet
          haxelib run lime setup --quiet
          haxelib install flixel-tools
          haxelib install flixel-ui --quiet
          haxelib install flixel-addons --quiet
          haxelib install hscript --quiet
          haxelib install newgrounds --quiet
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc --quiet
          haxelib git flixel-addons https://github.com/HaxeFlixel/flixel-addons --quiet
          haxelib install actuate --quiet
          haxelib git extension-webm https://github.com/KadeDev/extension-webm --quiet
          haxelib install openfl-webm
          lime rebuild extension-webm windows --quiet
          haxelib list
        shell: cmd
      - name: Create Version Tag
        run: echo "${{github.run_id}}" > VERSION
      - name: Compile
        run: haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
      - name: Publish Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: windowsBuild
          path: export/release/windows/bin
