jobs:
  build:
    runs-on: [ubuntu-latest,macos-latest]
    steps:
    - users: krdlab/setup-haxe@v1
      with:
        haxe-version: 4.0.5
    - run: |
      haxe -version
      haxelib install hxnodejs
